name: Generate Prisma Schema from SQL

on:
  push:
    paths:
      - 'LearningManagementSystems/**/*.sql'
      - '!**/*.prisma' # Не запускать, если меняется только .prisma
    branches:
      - main
      - master

jobs:
  generate-prisma:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Find SQL files
        id: find_sql
        run: |
          SQL_FILES=$(find LearningManagementSystems -name "*.sql" -type f)
          if [ -z "$SQL_FILES" ]; then
            echo "No SQL files found"
            exit 1
          fi
          echo "files=$SQL_FILES" >> $GITHUB_OUTPUT

      - name: Process each SQL file
        run: |
          while IFS= read -r sql_file; do
            echo "Processing $sql_file"

            # Определяем путь к Prisma-файлу
            prisma_file="${sql_file%.sql}.prisma"
            temp_db="/tmp/$(basename ${sql_file%.sql}).db"

            # Создаём временную SQLite базу
            sqlite3 "$temp_db" < "$sql_file"

            # Если Prisma-файл ещё не существует — создаём новый schema.prisma
            if [ ! -f "$prisma_file" ]; then
              mkdir -p "$(dirname "$prisma_file")"
              cat > "$prisma_file" << EOF
// Auto-generated from $sql_file
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = "file:$temp_db"
}

// Models will be added below
EOF
            fi

            # Интроспекция: получаем схему из SQL через SQLite
            npx prisma db pull --schema="$prisma_file" --force

            # Форматируем
            npx prisma format --schema="$prisma_file"

            echo "✅ Generated Prisma schema: $prisma_file"
          done <<< "$(find LearningManagementSystems -name "*.sql" -type f)"

      - name: Commit and Push Prisma files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Добавляем все .prisma файлы
          git add **/*.prisma

          # Проверяем, есть ли изменения
          if git diff-index --quiet HEAD --; then
            echo "✅ No changes to commit"
            exit 0
          else
            git commit -m "🤖 Auto-generate Prisma schema from SQL
            Generated via GitHub Actions when SQL was updated."
            git push origin HEAD:main
            echo "✅ Prisma schemas committed and pushed"
          fi
