name: Generate Prisma Schema from SQL

on:
  push:
    paths:
      - 'LearningManagementSystems/**/*.sql'
      - '!**/*.prisma'  # Не запускать, если меняются только .prisma файлы
    branches:
      - main
      - master

jobs:
  generate-prisma:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Process SQL files
        run: |
          find LearningManagementSystems -name "*.sql" | while read sql_file; do
            prisma_file="${sql_file%.sql}.prisma"
            temp_db="/tmp/$(basename "${sql_file%.sql}").db"

            echo "🔄 Processing $sql_file -> $prisma_file"

            sqlite3 "$temp_db" < "$sql_file"

            mkdir -p "$(dirname "$prisma_file")"

            printf 'generator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "sqlite"\n  url      = "file:%s"\n}\n' "$temp_db" > "$prisma_file"

            prisma db pull --schema="$prisma_file" --force
            prisma format --schema="$prisma_file"

            echo "✅ Generated $prisma_file"
          done

      - name: Commit and Push Prisma files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Добавляем все новые/изменённые .prisma файлы
          git add **/*.prisma

          # Проверяем, есть ли изменения для коммита
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto-generate Prisma schema from SQL. Automatically generated via GitHub Actions when SQL schema was updated."
            git push origin HEAD:${{ github.ref_name }}
            echo "✅ Изменения закоммичены и отправлены в ${{ github.ref_name }}"
          else
            echo "ℹ️ Изменений нет — коммит не требуется"
          fi
